# Cấu hình Cơ sở Dữ liệu
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:web2}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

# ORM
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false

# Log Debug
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# Tải file
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# JWT Secret Key (Cần được bảo mật tốt hơn trong môi trường sản xuất)
jwt_secret=123

# Swagger UI
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.doc-expansion=false
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui/index.html

# Đường dẫn ảnh
project.image=D:/projects/web2-java/uploads

# Cấu hình logging
logging.level.root=INFO
logging.level.com.backend.backend_java=DEBUG
logging.file.name=app.log

spring.main.allow-bean-definition-overriding=true

# Google OAuth2 Configuration

# spring.security.oauth2.client.registration.google.client-id=
# spring.security.oauth2.client.registration.google.client-secret=

# spring.security.oauth2.client.registration.google.client-id=your_client_id
# spring.security.oauth2.client.registration.google.client-secret=your_client-secret


spring.security.oauth2.client.registration.google.scope=openid,profile,email
# spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
# spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:3000/oauth2/redirect
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.registration.google.client-name=Google

# Base URL
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo


